"""Generate docs/reference/ssrs-reports.md from the SSRS .rdl files (data source, datasets/commands, parameters)."""
import glob, os, re, xml.etree.ElementTree as ET

from _options import ROOT as _ROOT, DOCS as _DOCS, SSRS_DIR, DATABASES

ROOT = os.path.join(_ROOT, SSRS_DIR) if SSRS_DIR else None
OUT = os.path.join(_DOCS, 'reference', 'ssrs-reports.md')


def local(tag):
    return tag.rsplit('}', 1)[-1]


def rows():
    for path in sorted(glob.glob(os.path.join(ROOT, '**', '*.rdl'), recursive=True)):
        root = ET.parse(path).getroot()
        sources, cmds, params = set(), [], []
        for el in root.iter():
            t = local(el.tag)
            if t == 'DataSourceReference' and el.text:
                sources.add(el.text.strip())
            elif t == 'DataSet':
                cmd_type, text = '', ''
                for c in el.iter():
                    if local(c.tag) == 'CommandType': cmd_type = (c.text or '').strip()
                    if local(c.tag) == 'CommandText': text = (c.text or '').strip()
                if cmd_type == 'StoredProcedure':
                    cmds.append(text)
                elif text:
                    procs = re.findall(r'(?i)\bexec(?:ute)?\s+(?:dbo\.)?\[?(\w+)', text)
                    cmds.append(', '.join(procs) if procs else 'inline SQL')
            elif t == 'ReportParameter':
                params.append(el.get('Name'))
        yield os.path.basename(path)[:-4], sorted(sources), sorted(set(cmds)), params


def main():
    def slug(*p):
        return re.sub(r"[^a-z0-9]+", "-", "-".join(p).lower()).strip("-")
    here = os.path.dirname(OUT)
    anchors = {}
    for page in [db['routines_page'] for db in DATABASES]:
        fp = os.path.join(here, page)
        if os.path.exists(fp):
            for a in re.findall(r'<a id="(sp-[^"]+)">', open(fp, encoding='utf-8').read()):
                anchors.setdefault(a, page)

    def link(proc):
        a = slug('sp', proc)
        return f"[{proc}]({anchors[a]}#{a})" if a in anchors else proc
    out = ['# SSRS reports', '', 'Generated by `docs/_tools/gen_ssrs.py` from `SSRS Reports/**/*.rdl`. Do not edit by hand. '
           'Dataset procedures link to the first database project (main, reporting, shared) that defines a routine with that name.', '',
           '<a id="index"></a>', '',
           '| Report | Data source | Datasets (procedure or inline SQL) | Parameters |', '| --- | --- | --- | --- |']
    n, used = 0, set()
    for name, src, cmds, params in rows():
        n += 1
        aid = slug("rpt", name)
        while aid in used:  # "Order Exception" and "Order_Exception" slug the same
            aid += "-2"
        used.add(aid)
        cl = '; '.join(', '.join(link(x.strip()) for x in c.split(',')) if c != 'inline SQL' else c for c in cmds)
        out.append(f'| <a id="{aid}"></a>**{name}** | {", ".join(src)} | {cl} | {", ".join(params)} |')
    out.insert(3, f'{n} reports.')
    open(OUT, 'w', encoding='utf-8').write('\n'.join(out) + '\n')
    print(n, 'reports ->', OUT)


if __name__ == '__main__':
    if ROOT and os.path.isdir(ROOT):
        main()
    else:
        print('no .rdl reports found; ssrs-reports.md not written')
