"""Generate inventory reference pages: Razor views, code components (services, helpers, repositories...),
models/view-models, and custom JavaScript. Everything is extracted from source; call relationships come from
the graphify knowledge graph (EXTRACTED edges only) plus exact name references in code.

Run from the workspace root:  python docs/_tools/gen_inventory.py
"""
import json
import os
import re
from collections import defaultdict

from gen_reference import ROOT, OUT, walk, read, rel, write, slug, anchor, md_escape, BACK
from _options import INVENTORY_PROJECTS, SCRIPTS_DIR, BUNDLE_CONFIG, WEB_PROJECT, CFG, is_custom_js

GRAPH = os.path.join(CFG.get("graph_dir", "graphify-out"), "graph.json")
PROJECTS = INVENTORY_PROJECTS
COMPONENT_DIRS = ("/Services/", "/Helpers/", "/Repositories/", "/BaseClasses/", "/Security/", "/Filters/", "/App_Start/",
                  "/Hubs/", "/Api/", "/Classes/", "/Interfaces/", "/Validators/")
COMPONENT_SUFFIX = ("Repository", "Service", "Helper", "Validator", "Retriever", "Builder", "Generator", "Uploader", "Reader",
                    "Manager", "Provider", "Filter", "Attribute", "Hub", "Handler", "Converter", "Action", "Module", "Config",
                    "Factory", "Exporter", "Engine", "Calculator", "Extensions", "Upload", "Client", "Mapper", "Rule")
CLASS_RE = re.compile(r"^\s*(?:public|internal)\s+(?:static\s+|abstract\s+|sealed\s+|partial\s+)*(class|interface|enum|struct)\s+(\w+)"
                      r"(?:<[^>]*>)?(?:\s*:\s*([^{\r\n]+))?", re.M)
METHOD_RE = re.compile(r"^\s*public\s+(?:static\s+|virtual\s+|override\s+|async\s+|new\s+)*([\w<>\[\],. ?]+?)\s+(\w+)\s*\(([^)]*)\)", re.M)


def is_generated(text):
    return "<auto-generated>" in text[:1500] or "This code was generated from a template" in text[:1500]


def project_of(r):
    return r.split("/")[0]


def area_of(r):
    return r.split("Areas/")[1].split("/")[0] if "Areas/" in r else "(root)"


def load_graph_calls():
    """file -> set(files) it calls, using EXTRACTED 'calls' edges only."""
    calls = defaultdict(set)
    if not os.path.exists(GRAPH):
        return calls
    g = json.load(open(GRAPH, encoding="utf-8"))
    src = {n["id"]: n.get("source_file") for n in g["nodes"]}
    for e in g["links"]:
        if e.get("relation") != "calls" or e.get("confidence") != "EXTRACTED":
            continue
        a, b = src.get(e["source"]), src.get(e["target"])
        if a and b and a != b:
            calls[os.path.relpath(a, ROOT).replace("\\", "/")].add(os.path.relpath(b, ROOT).replace("\\", "/"))
    return calls


def controller_anchor_map():
    m = {}
    for p in walk(ROOT, (".cs",)):
        r = rel(p)
        if "/Controllers/" not in r or project_of(r) not in PROJECTS:
            continue
        cm = re.search(r"public\s+(?:partial\s+)?class\s+(\w+Controller\w*)\b", read(p))
        if cm:
            m[(project_of(r), area_of(r), re.sub(r"Controller\w*$", "", cm.group(1)).lower())] = slug("ctl", project_of(r), area_of(r), cm.group(1))
            m[("file", r)] = m[(project_of(r), area_of(r), re.sub(r"Controller\w*$", "", cm.group(1)).lower())]
    return m


# ---------------------------------------------------------------- views
def gen_views(ctrl_map):
    rows = defaultdict(list)
    for p in sorted(walk(ROOT, (".cshtml", ".aspx", ".ascx"))):
        r = rel(p)
        if project_of(r) not in PROJECTS or "/Views/" not in r:
            continue
        t = read(p)
        folder = r.split("/Views/")[1].split("/")[0] if r.count("/") > r.index("/Views/") // 1 else ""
        parts = r.split("/Views/")[1].split("/")
        folder = parts[0] if len(parts) > 1 else "(root)"
        model = re.search(r"^\s*@model\s+([^\r\n]+)", t, re.M)
        layout = re.search(r'Layout\s*=\s*"([^"]+)"', t)
        partials = sorted(set(re.findall(r'(?:Html\.(?:Partial|RenderPartial)(?:Async)?)\(\s*"([^"]+)"', t)))
        child = sorted(set(f"{b}/{a}" if b else a for a, b in re.findall(r'Html\.(?:Action|RenderAction)\(\s*"([^"]+)"\s*(?:,\s*"([^"]+)")?', t)))
        urls = sorted(set(f"{b}/{a}" if b else a for a, b in re.findall(r'Url\.Action\(\s*"([^"]+)"\s*(?:,\s*"([^"]+)")?', t)))
        forms = sorted(set(f"{b}/{a}" if b else a for a, b in re.findall(r'(?:Html|Ajax)\.BeginForm\(\s*"([^"]+)"\s*(?:,\s*"([^"]+)")?', t)))
        scripts = sorted(set(os.path.basename(x) for x in re.findall(r'<script[^>]+src="[^"]*?([\w./-]+\.js)"', t)))
        rows[(project_of(r), area_of(r), folder)].append((r, model.group(1).strip() if model else "", layout.group(1) if layout else "",
                                                          partials, child, urls, forms, scripts, t.count("\n") + 1))
    total = sum(len(v) for v in rows.values())
    out = ["# Razor views", "",
           "Every view (`.cshtml`, plus the few WebForms `.aspx/.ascx`) in the application projects, extracted from source. "
           "Views are grouped by the controller folder they belong to; the folder name links to that controller's actions.", "",
           "- **Model**: the `@model` type the view renders.",
           "- **Renders**: partial views (`Html.Partial`) and child actions (`Html.Action`) the view pulls in.",
           "- **Calls**: controller actions the page calls from links, AJAX or scripts (`Url.Action`) and forms it posts (`BeginForm`).", "",
           f"Total views: {total}.", "", anchor("index"), "", "| Project / area | Folder | Views |", "| --- | --- | --- |"]
    for key in sorted(rows):
        out.append(f"| {key[0]} / {key[1]} | [{key[2]}](#{slug('views', *key)}) | {len(rows[key])} |")
    for key in sorted(rows):
        project, area, folder = key
        ca = ctrl_map.get((project, area, folder.lower()))
        cl = f" · Controller: [{folder}Controller](controllers.md#{ca})" if ca else ""
        out += ["", anchor(slug("views", *key)), "", f"## {project} / {area} / {folder}", "", f"{BACK}{cl}", "",
                "| View | Model | Renders | Calls | Scripts | Lines |", "| --- | --- | --- | --- | --- | --- |"]
        for r, model, layout, partials, child, urls, forms, scripts, lines in sorted(rows[key]):
            name = r.split("/")[-1]
            renders = ", ".join(partials + [f"action {c}" for c in child])
            calls = ", ".join(urls + [f"form → {f}" for f in forms])
            out.append(f"| {anchor(slug('view', r))}**{name}** | `{md_escape(model)}` | {md_escape(renders)} | {md_escape(calls)} | {', '.join(scripts)} | {lines} |")
    write("views.md", "\n".join(out) + "\n")
    return total


# ---------------------------------------------------------------- classes
def collect_classes():
    classes = []
    for p in sorted(walk(ROOT, (".cs",))):
        r = rel(p)
        if project_of(r) not in PROJECTS or r.endswith((".Designer.cs", "AssemblyInfo.cs")) or "/Web References/" in r:
            continue
        if "/Controllers/" in r and r.endswith("Controller.cs"):
            continue
        t = read(p)
        if is_generated(t):
            continue
        for m in CLASS_RE.finditer(t):
            kind, name, bases = m.group(1), m.group(2), (m.group(3) or "").strip().rstrip("{").strip()
            if kind == "enum":
                continue
            start = m.end()
            nxt = CLASS_RE.search(t, start)
            body = t[start: nxt.start() if nxt else len(t)]
            methods = []
            for mm in METHOD_RE.finditer(body):
                ret, mname = mm.group(1).strip(), mm.group(2)
                if mname == name or ret in ("class", "interface", "enum", "struct") or mname in ("Dispose",):
                    continue
                methods.append(mname)
            classes.append((r, kind, name, bases, sorted(set(methods))))
    return classes


def is_component(r, name):
    return any(d in "/" + r for d in COMPONENT_DIRS) or name.endswith(COMPONENT_SUFFIX)


def gen_classes(ctrl_map):
    classes = collect_classes()
    calls = load_graph_calls()
    names = defaultdict(list)
    for c in classes:
        names[c[2]].append(c[0])
    # exact whole-word references: class name -> files mentioning it (other than its own file)
    refs = defaultdict(set)
    word = re.compile(r"[A-Za-z_]\w+")
    wanted = set(names)
    for p in walk(ROOT, (".cs", ".cshtml")):
        r = rel(p)
        if project_of(r) not in PROJECTS or r.endswith((".Designer.cs",)):
            continue
        for w in set(word.findall(read(p))) & wanted:
            refs[w].add(r)
    file_anchor = {}
    comp, models = [], []
    for c in classes:
        (comp if is_component(c[0], c[2]) else models).append(c)
    for page, group in (("components.md", comp), ("models.md", models)):
        for c in group:
            file_anchor.setdefault(c[0], (page, slug("cls", c[0], c[2])))

    def flink(f, here):
        if f in file_anchor:
            page, a = file_anchor[f]
            return f"[{f.split('/')[-1][:-3]}]({'' if page == here else page}#{a})"
        if ("file", f) in ctrl_map:
            return f"[{f.split('/')[-1][:-3]}](controllers.md#{ctrl_map[('file', f)]})"
        return f"`{f.split('/')[-1]}`"

    def render(group, page, title, intro):
        by_folder = defaultdict(list)
        for c in group:
            folder = "/".join(c[0].split("/")[:-1])
            by_folder[folder].append(c)
        out = [f"# {title}", "", intro, "",
               "- **Calls into**: other code files this class calls (from the knowledge graph, extracted call edges only).",
               "- **Referenced by**: files that mention the class name (exact word match).", "",
               f"Total types: {len(group)} in {len(by_folder)} folders.", "", anchor("index"), "", "| Folder | Types |", "| --- | --- |"]
        for folder in sorted(by_folder):
            out.append(f"| [{folder}](#{slug('folder', page, folder)}) | {len(by_folder[folder])} |")
        for folder in sorted(by_folder):
            out += ["", anchor(slug("folder", page, folder)), "", f"## {folder}", "", BACK, ""]
            for r, kind, name, bases, methods in sorted(by_folder[folder], key=lambda c: c[2].lower()):
                callees = sorted(calls.get(r, set()) - {r})
                referers = sorted(refs.get(name, set()) - {r})
                out += [anchor(slug("cls", r, name)), "", f"### {name}", "",
                        f"`{kind}` in `{r}`" + (f" · inherits/implements `{md_escape(bases)}`" if bases else ""), ""]
                if methods:
                    out.append("**Public members:** " + ", ".join(f"`{m}`" for m in methods[:60]) + (" …" if len(methods) > 60 else ""))
                    out.append("")
                if callees:
                    out.append("**Calls into:** " + ", ".join(flink(f, page) for f in callees[:40]) + (" …" if len(callees) > 40 else ""))
                    out.append("")
                if referers:
                    out.append("**Referenced by:** " + ", ".join(flink(f, page) for f in referers[:40]) + (f" … (+{len(referers) - 40})" if len(referers) > 40 else ""))
                    out.append("")
        write(page, "\n".join(out) + "\n")

    render(comp, "components.md", "Code components (services, helpers, repositories, infrastructure)",
           "Every hand-written class and interface that carries behaviour: services, repositories, helpers, validators, "
           "file builders, filters, API actions and start-up configuration. Controllers are in [Controllers and actions](controllers.md); "
           "view models and data classes are in [Models and view models](models.md). EF-generated entity classes are omitted "
           "(their columns are in [Database tables](db-tables.md)).")
    render(models, "models.md", "Models and view models",
           "Every hand-written view model, metadata (validation) class, request/response DTO and other data class. "
           "EF-generated entity classes are omitted; their columns are in [Database tables](db-tables.md).")
    return len(comp), len(models)


# ---------------------------------------------------------------- javascript
def gen_js():
    base = os.path.join(ROOT, SCRIPTS_DIR)
    views = [(rel(p), read(p)) for p in walk(os.path.join(ROOT, WEB_PROJECT), (".cshtml",))]
    bp = os.path.join(ROOT, BUNDLE_CONFIG)
    bundle = read(bp) if os.path.exists(bp) else ""
    rows = []
    for p in sorted(walk(base, (".js",))):
        f = os.path.basename(p)
        if not is_custom_js(p):
            continue
        t = read(p)
        funcs = re.findall(r"^\s*function\s+(\w+)\s*\(|^\s*(?:var\s+)?([\w.]+)\s*=\s*function\s*\(", t, re.M)
        funcs = [a or b for a, b in funcs]
        used = sorted(r for r, txt in views if f in txt)
        in_bundle = f in bundle
        ajax = sorted(set(re.findall(r"['\"](/?[A-Z][\w]+/[A-Z][\w]+(?:/[A-Z][\w]+)?)['\"]", t)))
        rows.append((rel(p), t.count("\n") + 1, funcs, used, in_bundle, ajax))
    out = ["# Custom JavaScript", "",
           f"Every application-written script under `{SCRIPTS_DIR}` (third-party libraries such as jQuery, DataTables, "
           "Bootstrap and the Microsoft AJAX scripts are excluded). Functions are listed in file order.", "",
           anchor("index"), "", "| File | Lines | Functions | Bundled | Included by views |", "| --- | --- | --- | --- | --- |"]
    for r, n, funcs, used, b, _ in rows:
        out.append(f"| [{r.split('/')[-1]}](#{slug('js', r)}) | {n} | {len(funcs)} | {'yes' if b else ''} | {len(used)} |")
    for r, n, funcs, used, b, ajax in rows:
        out += ["", anchor(slug("js", r)), "", f"## {r.split('/')[-1]}", "", f"`{r}` · {n} lines · {BACK}", ""]
        if funcs:
            out += ["**Functions:** " + ", ".join(f"`{x}`" for x in funcs), ""]
        if ajax:
            out += ["**Server URLs referenced:** " + ", ".join(f"`{x}`" for x in ajax), ""]
        if b:
            out += [f"Included through `{BUNDLE_CONFIG}`.", ""]
        if used:
            out += ["**Included by views:** " + ", ".join(f"[{u.split('/')[-1]}](views.md#{slug('view', u)})" for u in used), ""]
    write("javascript.md", "\n".join(out) + "\n")
    return len(rows)


if __name__ == "__main__":
    cm = controller_anchor_map()
    print("views", gen_views(cm))
    print("components/models", gen_classes(cm))
    print("js", gen_js())
