"""Site furniture the skill owns, refreshed on every build_site.py run:

- docs/assets/site-theme.css (the site's look) and docs/assets/fonts/ (IBM Plex, SIL OFL), loaded before the project's
  extra.css; an extra.css or logo.svg still identical to the previous template is upgraded, an edited one is left alone;
- docs/assets/readability.css (sticky table headers, readable line length) and its mkdocs.yml extra_css entry;
- the theme font: the template default (Inter from Google Fonts) becomes system fonts, so the offline site makes no
  internet requests; a font the project chose itself is left alone;
- docs/_src/getting-started/how-to-use.md, a reader's guide built from the pages that actually exist.
"""
import glob
import os
import re
import shutil

from _common import SKILL_DIR

GUIDE = os.path.join("getting-started", "how-to-use.md")
MARK = "<!-- generated by build_site.py (reader_guide.py): edits are overwritten on the next build -->"


def title_of(path):
    for line in open(path, encoding="utf-8", errors="ignore"):
        if line.startswith("# "):
            return line[2:].strip()
    return os.path.splitext(os.path.basename(path))[0].replace("-", " ").capitalize()


OLD_DEFAULT_ACCENT = "#3f51b5"  # the previous template default; an untouched copy moves to the current default
DEFAULT_ACCENT = "#0b6e74"


def upgrade_stock_theme(docs):
    """extra.css and logo.svg belong to the project once written. Only a copy still identical to the previous template
    (any accent) is replaced with the current one, so a project's own edits are never overwritten."""
    tdir = os.path.join(SKILL_DIR, "templates")
    extra = os.path.join(docs, "assets", "extra.css")
    old_tmpl = os.path.join(tdir, "legacy", "extra.css.v1.tmpl")
    if os.path.exists(extra) and os.path.exists(old_tmpl):
        pat = re.escape(open(old_tmpl, encoding="utf-8").read().strip()).replace(re.escape("{{accent_hex}}"), r"(#[0-9a-fA-F]{3,8})")
        m = re.fullmatch(pat, open(extra, encoding="utf-8").read().replace("\r\n", "\n").strip())
        if m:
            accent = DEFAULT_ACCENT if m.group(1).lower() == OLD_DEFAULT_ACCENT else m.group(1)
            new = open(os.path.join(tdir, "extra.css.tmpl"), encoding="utf-8").read().replace("{{accent_hex}}", accent)
            open(extra, "w", encoding="utf-8", newline="\n").write(new)
    logo = os.path.join(docs, "assets", "logo.svg")
    old_logo = os.path.join(tdir, "legacy", "logo.v1.svg")
    if os.path.exists(logo) and os.path.exists(old_logo) and open(logo, encoding="utf-8").read().strip() == open(old_logo, encoding="utf-8").read().strip():
        shutil.copy2(os.path.join(tdir, "assets", "logo.svg"), logo)


def add_extra_css(text, entry, first=False):
    """Register a stylesheet in mkdocs.yml's extra_css list (first = before the project's own files)."""
    if entry in text:
        return text
    m = re.search(r"^extra_css:[ \t]*\n((?:[ \t]+-.*\n)*)", text, re.M)
    if not m:
        return text.rstrip("\n") + f"\n\nextra_css:\n  - {entry}\n"
    at = m.start(1) if first else m.end(1)
    return text[:at] + f"  - {entry}\n" + text[at:]


def site_assets(docs, yml="mkdocs.yml"):
    assets = os.path.join(SKILL_DIR, "templates", "assets")
    os.makedirs(os.path.join(docs, "assets"), exist_ok=True)
    for name in ("readability.css", "site-theme.css"):
        shutil.copy2(os.path.join(assets, name), os.path.join(docs, "assets", name))
    if os.path.isdir(os.path.join(assets, "fonts")):  # IBM Plex (SIL OFL), served locally so the site stays offline
        shutil.copytree(os.path.join(assets, "fonts"), os.path.join(docs, "assets", "fonts"), dirs_exist_ok=True)
    upgrade_stock_theme(docs)
    if not os.path.exists(yml):
        return
    text = open(yml, encoding="utf-8").read()
    new = add_extra_css(text, "assets/site-theme.css", first=True)
    new = add_extra_css(new, "assets/readability.css")
    # only the template's own default is replaced; any other font choice is the project's
    new = re.sub(r"^  font:\n    text: Inter\n    code: JetBrains Mono\n", "  font: false\n", new, count=1, flags=re.M)
    if new != text:
        open(yml, "w", encoding="utf-8", newline="\n").write(new)


def write_guide(docs, cfg):
    src = os.path.join(docs, "_src")
    if not os.path.isdir(os.path.join(src, "getting-started")):
        return
    product = cfg.get("product") or "the product"

    def link(rel, text):  # only pages that exist, so the guide never adds a broken link
        return f"[{text}](../{rel})" if os.path.exists(os.path.join(src, rel)) or os.path.exists(os.path.join(docs, rel)) else text

    sections = []
    order = ["architecture", "modules", "workflows", "integrations", "data", "shared", "operations", "security", "how-to", "appendices"]
    dirs = [x for x in os.listdir(src) if os.path.isdir(os.path.join(src, x)) and x != "getting-started"]
    for d in sorted(dirs, key=lambda x: (order.index(x) if x in order else len(order), x)):  # the site's own section order
        idx = os.path.join(src, d, "index.md")
        if os.path.exists(idx):
            sections.append(f"[{title_of(idx)}](../{d}/index.md)")
    refs = sorted(glob.glob(os.path.join(docs, "reference", "*.md")))
    sensitive = [s for s in cfg.get("sensitive", []) if os.path.exists(os.path.join(docs, s))]
    out = [f"# How to use these docs", "", "<!-- nav: 1 -->", MARK, "",
           "## Where to start", "",
           f"- New to {product}: read {link('getting-started/product-overview.md', 'the product overview')}, then "
           f"{link('architecture/index.md', 'the architecture')}.",
           "- Looking for one thing (a class, table, setting or screen): use search.",
           "- Changing code: start from the reference page for what you are changing, then follow its links to the "
           "workflows and data it touches.", ""]
    exists = lambda rel: os.path.exists(os.path.join(src, rel))  # noqa: E731
    roles = [(who, [link(rel, text) for rel, text in pages if exists(rel)]) for who, pages in (
        ("Business analyst or product owner", [("modules/index.md", "business modules"), ("workflows/index.md", "workflows")]),
        ("Developer", [("architecture/index.md", "architecture"), ("data/index.md", "data model"), ("shared/index.md", "shared code")]),
        ("Architect", [("architecture/index.md", "architecture"), ("integrations/index.md", "integrations"), ("security/index.md", "security")]),
        ("Operations and support", [("operations/index.md", "operations"), ("integrations/index.md", "integrations")]))]
    roles = [(who, ls) for who, ls in roles if ls]
    if roles:
        out += ["### By role", ""] + [f"- **{who}:** {', then '.join(ls)}." for who, ls in roles] + [""]
    out += ["## Finding things", "",
           "- **Search** works offline. Press <kbd>/</kbd> or <kbd>S</kbd> to start typing.",
           "- **Tabs** along the top are the sections; the left sidebar lists the pages in a section; the right sidebar "
           "lists the headings on the current page.",
           "- <kbd>N</kbd> and <kbd>P</kbd> move to the next and previous page.",
           "- **Names are links.** Classes, tables, procedures, settings and screens named in the text link to their "
           "reference entry.", "",
           "## Two kinds of page", "",
           "- **Explanations** describe how the system works and why. They are written from the source code and checked "
           "against it. Their counts are filled in from the generated reference each time the site is built, wherever the "
           "writer used a count tag (the build flags hand-typed counts that should be tags).",
           ]
    if sections:
        out.append("  Sections: " + ", ".join(sections) + ".")
    out += ["- **Reference pages** are generated from the code on every build and list everything of their kind:", ""]
    out += [f"    - [{title_of(r)}](../reference/{os.path.basename(r)})" for r in refs] or ["    - (none generated yet)"]
    out += ["", "## Reading a reference table", "",
            "- Long tables scroll inside their own box, so the column headers stay in view.",
            "- Locations are given as `file:line` relative to the source tree.",
            f"- {link('appendices/coverage.md', 'The coverage appendix')} shows how much of each kind of item the "
            "explanations discuss.", "",
            "## For coding agents", "",
            "- `AGENTS.md`, the project skill, `llms.txt` and the entity index let a coding agent answer questions "
            "from these docs and jump to `file:line` in the source. The package README explains the setup."]
    if sensitive:
        out += ["", "## Pages to share privately", "",
                "- These pages describe security weaknesses; share them only with people who need them: "
                + ", ".join(f"[{title_of(os.path.join(docs, s))}](../{s})" for s in sensitive) + "."]
    path = os.path.join(src, GUIDE)
    text = "\n".join(out) + "\n"
    if not os.path.exists(path) or open(path, encoding="utf-8").read() != text:
        open(path, "w", encoding="utf-8", newline="\n").write(text)
