"""Site furniture the skill owns, refreshed on every build_site.py run:

- docs/assets/readability.css (sticky table headers, readable line length) and its mkdocs.yml extra_css entry;
- the theme font: the template default (Inter from Google Fonts) becomes system fonts, so the offline site makes no
  internet requests; a font the project chose itself is left alone;
- docs/_src/getting-started/how-to-use.md, a reader's guide built from the pages that actually exist.
"""
import glob
import os
import re
import shutil

from _common import SKILL_DIR

GUIDE = os.path.join("getting-started", "how-to-use.md")
MARK = "<!-- generated by build_site.py (reader_guide.py): edits are overwritten on the next build -->"


def title_of(path):
    for line in open(path, encoding="utf-8", errors="ignore"):
        if line.startswith("# "):
            return line[2:].strip()
    return os.path.splitext(os.path.basename(path))[0].replace("-", " ").capitalize()


def site_assets(docs, yml="mkdocs.yml"):
    os.makedirs(os.path.join(docs, "assets"), exist_ok=True)
    shutil.copy2(os.path.join(SKILL_DIR, "templates", "assets", "readability.css"), os.path.join(docs, "assets", "readability.css"))
    if not os.path.exists(yml):
        return
    text = open(yml, encoding="utf-8").read()
    new = text
    if "assets/readability.css" not in new:
        if re.search(r"^extra_css:\s*$", new, re.M):
            new = re.sub(r"^(extra_css:\s*\n(?:[ \t]+-.*\n)*)", r"\1  - assets/readability.css\n", new, count=1, flags=re.M)
        else:
            new = new.rstrip("\n") + "\n\nextra_css:\n  - assets/readability.css\n"
    # only the template's own default is replaced; any other font choice is the project's
    new = re.sub(r"^  font:\n    text: Inter\n    code: JetBrains Mono\n", "  font: false\n", new, count=1, flags=re.M)
    if new != text:
        open(yml, "w", encoding="utf-8", newline="\n").write(new)


def write_guide(docs, cfg):
    src = os.path.join(docs, "_src")
    if not os.path.isdir(os.path.join(src, "getting-started")):
        return
    product = cfg.get("product") or "the product"

    def link(rel, text):  # only pages that exist, so the guide never adds a broken link
        return f"[{text}](../{rel})" if os.path.exists(os.path.join(src, rel)) or os.path.exists(os.path.join(docs, rel)) else text

    sections = []
    order = ["architecture", "modules", "workflows", "integrations", "data", "shared", "operations", "security", "how-to", "appendices"]
    dirs = [x for x in os.listdir(src) if os.path.isdir(os.path.join(src, x)) and x != "getting-started"]
    for d in sorted(dirs, key=lambda x: (order.index(x) if x in order else len(order), x)):  # the site's own section order
        idx = os.path.join(src, d, "index.md")
        if os.path.exists(idx):
            sections.append(f"[{title_of(idx)}](../{d}/index.md)")
    refs = sorted(glob.glob(os.path.join(docs, "reference", "*.md")))
    sensitive = [s for s in cfg.get("sensitive", []) if os.path.exists(os.path.join(docs, s))]
    out = [f"# How to use these docs", "", "<!-- nav: 1 -->", MARK, "",
           "## Where to start", "",
           f"- New to {product}: read {link('getting-started/product-overview.md', 'the product overview')}, then "
           f"{link('architecture/index.md', 'the architecture')}.",
           "- Looking for one thing (a class, table, setting or screen): use search.",
           "- Changing code: start from the reference page for what you are changing, then follow its links to the "
           "workflows and data it touches.", "",
           "## Finding things", "",
           "- **Search** works offline. Press <kbd>/</kbd> or <kbd>S</kbd> to start typing.",
           "- **Tabs** along the top are the sections; the left sidebar lists the pages in a section; the right sidebar "
           "lists the headings on the current page.",
           "- <kbd>N</kbd> and <kbd>P</kbd> move to the next and previous page.",
           "- **Names are links.** Classes, tables, procedures, settings and screens named in the text link to their "
           "reference entry.", "",
           "## Two kinds of page", "",
           "- **Explanations** describe how the system works and why. They are written from the source code and checked "
           "against it. Their counts are filled in from the generated reference each time the site is built, wherever the "
           "writer used a count tag (the build flags hand-typed counts that should be tags).",
           ]
    if sections:
        out.append("  Sections: " + ", ".join(sections) + ".")
    out += ["- **Reference pages** are generated from the code on every build and list everything of their kind:", ""]
    out += [f"    - [{title_of(r)}](../reference/{os.path.basename(r)})" for r in refs] or ["    - (none generated yet)"]
    out += ["", "## Reading a reference table", "",
            "- Long tables scroll inside their own box, so the column headers stay in view.",
            "- Locations are given as `file:line` relative to the source tree.",
            f"- {link('appendices/coverage.md', 'The coverage appendix')} shows how much of each kind of item the "
            "explanations discuss.", "",
            "## For coding agents", "",
            "- `AGENTS.md`, the project skill, `llms.txt` and the entity index let a coding agent answer questions "
            "from these docs and jump to `file:line` in the source. The package README explains the setup."]
    if sensitive:
        out += ["", "## Pages to share privately", "",
                "- These pages describe security weaknesses; share them only with people who need them: "
                + ", ".join(f"[{title_of(os.path.join(docs, s))}](../{s})" for s in sensitive) + "."]
    path = os.path.join(src, GUIDE)
    text = "\n".join(out) + "\n"
    if not os.path.exists(path) or open(path, encoding="utf-8").read() != text:
        open(path, "w", encoding="utf-8", newline="\n").write(text)
