"""Code & data map: every class (from components.md) and every table / routine (from the SQL reference pages) placed in
a business area, written as a NARRATIVE source page (docs/_src/appendices/code-map.md) with link tags, so the coverage
report counts each item as discussed and readers can browse the system by business area.

Area assignment (deterministic, first rule wins):
  1. adapter_options["generic-areas"]["rules"]: [{"area": "Orders", "regex": "order|invoice"}, ...]  (matched on the name,
     then on the file path)
  2. classes: their graphify community name; tables / routines: the first word of the name (Order_Line -> Order)
Run by build_site.py after the other adapters (cwd = workspace root).
"""
import json
import os
import re
from collections import defaultdict

CFG = json.load(open("codebase-docs.json", encoding="utf-8"))
DOCS = CFG.get("docs_dir", "docs")
REF = os.path.join(DOCS, "reference")
OPT = CFG.get("adapter_options", {}).get("generic-areas", {})
RULES = [(r["area"], re.compile(r["regex"], re.I)) for r in OPT.get("rules", [])]
OUT = os.path.join(DOCS, "_src", "appendices", "code-map.md")
STOP = {"dd", "fn", "sp", "usp", "tbl", "vw", "v", "get", "set", "is", "has", "allow", "can", "do", "p", "f", "t", "x", "tr", "trg",
        "ins", "upd", "del", "sel", "insert", "update", "delete", "select", "dbo", "temp", "tmp", "fnget", "udf"}


def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def by_rule(name, path=""):
    for area, rx in RULES:
        if rx.search(name) or (path and rx.search(path)):
            return area
    return None


def main():
    areas = defaultdict(lambda: {"classes": [], "routines": [], "tables": []})
    comp = os.path.join(REF, "components.md")
    if os.path.exists(comp):
        comm_of = {}
        cpath = os.path.join(REF, "communities.md")
        if os.path.exists(cpath):
            cur = None
            for line in open(cpath, encoding="utf-8"):
                h = re.match(r"## (.+)", line)
                if h:
                    cur = h.group(1).strip()
                for a in re.findall(r"\(#((?:cls|fn)-[^)]+)\)", line):
                    if cur:
                        comm_of[a] = cur
        rows = []
        for line in open(comp, encoding="utf-8"):
            m = re.match(r'\| <a id="((?:cls|fn)-[^"]+)"></a>\*\*([^*]+)\*\*.*?\| `([^`]+)`', line)
            if m:
                rows.append(m.groups())
        size = defaultdict(int)
        for aid, _, _ in rows:
            size[comm_of.get(aid)] += 1
        min_comm = OPT.get("min_community_size", max(8, len(rows) // 150))  # tiny communities fall back to folders
        for aid, name, path in rows:
            c = comm_of.get(aid)
            folder = "/".join(path.split("/")[:-1][:3]) or "(root)"
            area = by_rule(name, path) or (c if c and size[c] >= min_comm and not re.match(r"(?i)community \d+$", c) else folder)
            areas[area]["classes"].append((name, aid))
    for page, kind in (("db-routines.md", "routines"), ("db-tables.md", "tables")):
        p = os.path.join(REF, page)
        if not os.path.exists(p):
            continue
        for a, name in re.findall(r'<a id="((?:sp|tbl)-[^"]+)"></a>(?:\s*\n\s*##\s*(?:\w+\.)?|\*\*)(\w+)', open(p, encoding="utf-8").read()):
            toks = [t for t in re.split(r"_|(?<=[a-z])(?=[A-Z])", name) if t]
            while len(toks) > 1 and toks[0].lower() in STOP:
                toks = toks[1:]
            area = by_rule(name) or (toks[0].title() if toks else name)
            areas[area][kind].append((name, a))
    if not areas:
        print("area-map: nothing to map (no components.md / SQL reference)")
        return
    small = [k for k, v in areas.items() if sum(len(x) for x in v.values()) < OPT.get("min_area_items", 3)]
    if len(areas) > 40:  # fold tiny areas into "Other — <top folder>" so the map stays readable
        for k in small:
            v = areas.pop(k)
            top = k.split("/")[0] if "/" in k else "misc"
            for kind, items in v.items():
                areas[f"Other — {top}"][kind].extend(items)
    out = ["# Code & data map", "", "<!-- nav: 90 -->", "",
           "Every class, table and routine placed in the business area it serves, so the system can be browsed by area. "
           "Generated by `area_map.py`; names link to their full reference entries.", "", "| Area | Classes | Tables | Routines |",
           "| --- | ---: | ---: | ---: |"]
    order = sorted(areas, key=lambda k: (-sum(len(v) for v in areas[k].values()), k))
    for k in order:
        v = areas[k]
        out.append(f"| [{k}](#{slug(k)}) | {len(v['classes'])} | {len(v['tables'])} | {len(v['routines'])} |")
    for k in order:
        v = areas[k]
        out += ["", f'<a id="{slug(k)}"></a>', "", f"## {k}", ""]
        if v["tables"]:
            out += ["**Tables:** " + ", ".join(f"[[table:{n}]]" for n, _ in sorted(set(v["tables"]))), ""]
        if v["routines"]:
            out += ["**Routines:** " + ", ".join(f"[[proc:{n}]]" for n, _ in sorted(set(v["routines"]))), ""]
        if v["classes"]:
            out += ["**Classes & functions:** " + ", ".join(f"[[{a.split('-')[0]}:{n}]]" for n, a in sorted(set(v["classes"]))), ""]
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print(f"area-map: {len(areas)} areas -> {OUT}")


if __name__ == "__main__":
    main()
