"""Business-flow pages and the interactive flow viewer, from small JSON specs written during research.

Input:  docs/_src/workflows/flows/<id>.flow.json   (format: reference/flows.md; draft one with trace_flow.py --draft)
Output: docs/_src/workflows/flows/<id>.md           flow page: summary, embedded interactive chart, Mermaid flowchart
                                                    (static fallback), optional sequence diagram, step table with link tags
        docs/_src/workflows/flows/index.md          catalogue of all flows
        docs/assets/flows/index.html                self-contained, offline viewer: swimlanes, click a step for its code
                                                    (declaration, calls, called by), walk-through, search, zoom / pan
Generated pages carry a marker; edit the .flow.json, never the .md. A step "ref" that resolves to no reference anchor
fails the adapter (nothing in a flow is unlinked by accident). Run last (after the other adapters), like generic-areas.
"""
import json
import os
import re
import sys
from collections import defaultdict
from _stats import stat  # noqa: E402  (headline numbers for [[n:...]] tags)

CFG = json.load(open("codebase-docs.json", encoding="utf-8"))
DOCS = CFG.get("docs_dir", "docs")
REF = os.path.join(DOCS, "reference")
FLOWS = os.path.join(DOCS, "_src", "workflows", "flows")
VIEWER = os.path.join(DOCS, "assets", "flows", "index.html")
TEMPLATE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "templates", "flows-viewer.html")
MARK = "<!-- generated by flow_pages.py"
TAG = re.compile(r"\[\[(\w+):([^\]|]+)(?:\|([^\]]+))?\]\]")
ALIAS = {"table": "tbl", "proc": "sp"}
KINDS = {"step", "decision", "data", "external", "start", "end"}


def slug(*parts):
    return re.sub(r"[^a-z0-9]+", "-", "-".join(str(p) for p in parts).lower()).strip("-")


def anchors():
    out, by_prefix = {}, defaultdict(list)
    for page in sorted(os.listdir(REF)) if os.path.isdir(REF) else []:
        if page.endswith(".md"):
            for a in re.findall(r'<a id="([^"]+)"', open(os.path.join(REF, page), encoding="utf-8").read()):
                if a not in out:
                    out[a] = page
                    by_prefix[a.split("-")[0]].append(a)
    return out, by_prefix


def resolve(tag, idx):
    """'mth:Class.Method' / 'table:Orders' / 'page:x.md#y' -> (page, anchor) or None. Same rules as build_docs (exact, then suffix)."""
    kind, _, name = tag.partition(":")
    name = name.split("|")[0].strip()
    if kind == "page":
        path = name.partition("#")[0]
        return ("page", name) if os.path.exists(os.path.join(DOCS, "_src", path)) else None
    out, by_prefix = idx
    prefix = ALIAS.get(kind, kind)
    names = [name]
    if kind == "act" and "." in name:
        c, m = name.rsplit(".", 1)
        names.append((c if c.lower().endswith("controller") else c + "Controller") + "." + m)
    for n in names:
        a = slug(prefix, n)
        if a in out:
            return out[a], a
        cands = sorted((x for x in by_prefix.get(prefix, []) if x.endswith("-" + slug(n))), key=len)
        if cands:
            return out[cands[0]], cands[0]
    return None


def plain(s):
    return TAG.sub(lambda m: m.group(3) or m.group(2).split(".")[-1] if m.group(1) != "mth" else (m.group(3) or m.group(2)), str(s or ""))


def mm(s):
    return plain(s).replace('"', "#quot;").replace("\n", " ")


def main():
    specs = sorted(f for f in os.listdir(FLOWS) if f.endswith(".flow.json")) if os.path.isdir(FLOWS) else []
    if os.path.isdir(FLOWS):  # drop generated pages whose spec is gone
        for f in os.listdir(FLOWS):
            if f.endswith(".md") and f != "index.md" and not os.path.exists(os.path.join(FLOWS, f[:-3] + ".flow.json")):
                p = os.path.join(FLOWS, f)
                if open(p, encoding="utf-8").read().startswith(MARK):
                    os.remove(p)
    if not specs:
        print("flows: none yet (write docs/_src/workflows/flows/<id>.flow.json; see reference/flows.md)")
        return
    idx = anchors()
    mpath = os.path.join(DOCS, "agent", "methods.json")
    methods = json.load(open(mpath, encoding="utf-8")) if os.path.exists(mpath) else {}
    epath = os.path.join(DOCS, "agent", "endpoints.json")
    by_handler = defaultdict(list)  # method anchor -> endpoints it serves (with "callers" from the generic-api adapter)
    for ep in (json.load(open(epath, encoding="utf-8")) if os.path.exists(epath) else []):
        if ep.get("handler"):
            by_handler[ep["handler"]].append(ep)
    errors, warnings, flows = [], [], []
    for fname in specs:
        try:
            f = json.load(open(os.path.join(FLOWS, fname), encoding="utf-8"))
        except ValueError as ex:
            errors.append(f"{fname}: invalid JSON ({ex})")
            continue
        fid = f.get("id") or fname[:-10]
        steps = f.get("steps") or []
        ids = [s.get("id") for s in steps]
        if not steps or None in ids or len(set(ids)) != len(ids):
            errors.append(f"{fname}: every step needs a unique id")
            continue
        lanes = list(f.get("lanes") or [])
        for s in steps:
            s.setdefault("lane", lanes[0] if lanes else "Flow")
            if s["lane"] not in lanes:
                lanes.append(s["lane"])
            if s.get("kind", "step") not in KINDS:
                errors.append(f"{fname}: step {s['id']}: kind must be one of {', '.join(sorted(KINDS))}")
        edges = []
        for k, s in enumerate(steps):
            nxt = s.get("next")
            if nxt is None:
                nxt = [] if s.get("kind") == "end" or k == len(steps) - 1 else [steps[k + 1]["id"]]
            for n in (nxt if isinstance(nxt, list) else [nxt]):
                to, label = (n.get("to"), n.get("label", "")) if isinstance(n, dict) else (n, "")
                if to not in ids:
                    errors.append(f"{fname}: step {s['id']}: next '{to}' is not a step id")
                    continue
                edges.append({"from": s["id"], "to": to, "label": label})
        out_steps = []
        for s in steps:
            refs = s.get("ref") or []
            refs = [refs] if isinstance(refs, str) else refs
            tags = [f"{m.group(1)}:{m.group(2)}" for m in TAG.finditer(" ".join(str(s.get(k, "")) for k in ("text", "data", "note")))]
            links = []
            for r in refs + tags:
                hit = resolve(r, idx)
                if not hit:
                    if r in refs:
                        errors.append(f"{fname}: step {s['id']}: ref '{r}' matches no reference entry")
                    continue
                page, a = hit
                if (s.get("kind") == "start" or s is steps[0]) and r in refs:
                    # a flow must start where users or jobs really enter: an action no screen calls is the wrong path
                    eps = by_handler.get(a, [])
                    if eps and all(ep.get("callers") == 0 for ep in eps):
                        warnings.append(f"{fname}: step {s['id']} starts at {r}, but no script, view or form in the repository "
                                        f"calls {eps[0]['route']}: check which action the screen really posts to "
                                        f"(trace_calls.py <method> --entry, or search the scripts for the URL)")
                    elif not eps and a in methods and not methods[a].get("callers") and not methods[a].get("entry_points"):
                        warnings.append(f"{fname}: step {s['id']} starts at {r}, which nothing in the code calls")
                if page == "page":
                    path, _, frag = a.partition("#")
                    links.append({"label": r.split(":", 1)[1], "url": "../../" + path[:-3] + ".html" + ("#" + frag if frag else "")})
                    continue
                link = {"label": r.split(":", 1)[1].split("|")[0], "url": f"../../reference/{page[:-3]}.html#{a}"}
                x = methods.get(a)
                if x:
                    link.update(label=x["name"], file=x["file"], line=x["line"], decl=x["decl"],
                                calls=[methods[c]["name"] for c in x["calls"] if c in methods][:8],
                                callers=[methods[c]["name"] for c in x["callers"] if c in methods][:8])
                links.append(link)
            out_steps.append({"id": s["id"], "lane": s["lane"], "kind": s.get("kind", "step"), "label": plain(s.get("text", s["id"])),
                              "data": plain(s.get("data", "")), "note": plain(s.get("note", "")), "links": links,
                              "_refs": refs, "_raw": s})
        flows.append({"id": fid, "title": f.get("title") or fid, "module": plain(f.get("module", "")), "summary": plain(f.get("summary", "")),
                      "trigger": plain(f.get("trigger", "")), "outcome": plain(f.get("outcome", "")), "lanes": lanes,
                      "steps": out_steps, "edges": edges, "notes": [plain(n) for n in f.get("notes") or []],
                      "page": f"../../workflows/flows/{fid}.html", "_spec": f, "_file": fname, "sequence": bool(f.get("sequence"))})

    for fl in flows:
        write_page(fl)
    write_index(flows)
    data = [{k: v for k, v in fl.items() if not k.startswith("_")} for fl in flows]
    for fl in data:
        fl["steps"] = [{k: v for k, v in s.items() if not k.startswith("_")} for s in fl["steps"]]
    html = open(TEMPLATE, encoding="utf-8").read().replace("/*FLOWS_DATA*/", json.dumps(data, ensure_ascii=False).replace("</", "<\\/"))
    os.makedirs(os.path.dirname(VIEWER), exist_ok=True)
    open(VIEWER, "w", encoding="utf-8", newline="\n").write(html)
    nsteps = sum(len(fl["steps"]) for fl in flows)
    linked = sum(1 for fl in flows for s in fl["steps"] if s["links"])
    stat("flows", flows=len(flows), steps=nsteps)
    print(f"flows: {len(flows)} flows, {nsteps} steps ({linked} linked to code), viewer {VIEWER}")
    if warnings:
        print("\n".join("WARNING " + w for w in warnings))
    if errors:
        print("\n".join("ERROR " + e for e in errors))
        sys.exit(1)


SHAPE = {"decision": ('{"', '"}'), "data": ('[("', '")]'), "external": ('[["', '"]]'), "end": ('(["', '"])'), "start": ('(["', '"])')}


def write_page(fl):
    f, sid = fl["_spec"], {s["id"]: f"n{k}" for k, s in enumerate(fl["steps"])}
    lines = [f"{MARK} from {fl['_file']}: edit the JSON, not this page -->", f"# {fl['title']}", ""]
    if f.get("summary"):
        lines += [f["summary"], ""]
    rows = [(k.title(), f.get(k)) for k in ("module", "trigger", "outcome") if f.get(k)]
    rows.append(("Lanes", ", ".join(fl["lanes"])))
    lines += ["| | |", "| --- | --- |"] + [f"| {k} | {v} |" for k, v in rows] + [""]
    lines += [f'<iframe src="../../assets/flows/index.html#{fl["id"]}&embed" title="{fl["title"]} (interactive)" '
              'style="width:100%;height:640px;border:1px solid var(--md-default-fg-color--lightest);border-radius:6px" loading="lazy"></iframe>', "",
              f"[Open the interactive chart full screen](../../assets/flows/index.html#{fl['id']}): click a step for its code, "
              "use ← → to walk through the steps.", "", "## Flowchart", "",
              "The same flow as a static diagram (renders on GitHub and in print), one box per lane.", "", "```mermaid", "flowchart TD"]
    for lane in fl["lanes"]:
        lines.append(f'  subgraph L{fl["lanes"].index(lane)}["{mm(lane)}"]')
        for s in fl["steps"]:
            if s["lane"] == lane:
                a, b = SHAPE.get(s["kind"], ('["', '"]'))
                lines.append(f"    {sid[s['id']]}{a}{mm(s['label'])}{b}")
        lines.append("  end")
    for e in fl["edges"]:
        lines.append(f"  {sid[e['from']]} -->{'|' + mm(e['label']) + '|' if e['label'] else ''} {sid[e['to']]}")
    lines += ["```", ""]
    if fl["sequence"] and len(fl["lanes"]) > 1:
        lines += ["## Sequence", "", "Who hands over to whom, in step order.", "", "```mermaid", "sequenceDiagram"] + [f"  participant L{k} as {mm(l)}" for k, l in enumerate(fl["lanes"])]
        prev = None
        for s in fl["steps"]:
            li = fl["lanes"].index(s["lane"])
            text = ("Decision: " if s["kind"] == "decision" else "") + mm(s["label"]).replace(";", ",")
            lines.append(f"  L{prev}->>L{li}: {text}" if prev is not None and prev != li else f"  Note over L{li}: {text}")
            prev = li
        lines += ["```", ""]
    lines += ["## Steps", "", "| # | Lane | Step | Code | Data and notes |", "| ---: | --- | --- | --- | --- |"]
    for k, s in enumerate(fl["steps"], 1):
        raw = s["_raw"]
        code = ", ".join(f"[[{r}]]" for r in s["_refs"]) or "—"
        nxt = [e for e in fl["edges"] if e["from"] == s["id"] and e["label"]]
        branch = "; ".join(f"{e['label']} → step {[x['id'] for x in fl['steps']].index(e['to']) + 1}" for e in nxt)
        extra = " · ".join(x for x in (raw.get("data", ""), raw.get("note", ""), branch) if x)
        kind = f" ({s['kind']})" if s["kind"] not in ("step",) else ""
        lines.append(f"| {k} | {s['lane']} | {raw.get('text', s['id'])}{kind} | {code} | {extra or '—'} |".replace("\n", " "))
    if f.get("notes"):
        lines += ["", "## Notes", ""] + [f"- {n}" for n in f["notes"]]
    lines += ["", "[All flows](index.md)", ""]
    open(os.path.join(FLOWS, fl["id"] + ".md"), "w", encoding="utf-8", newline="\n").write("\n".join(lines))


def write_index(flows):
    lines = [f"{MARK}: one row per .flow.json in this folder -->", "# Business flows", "",
             "Each flow follows one business journey step by step, lane by lane, with every step linked to the code that does it. "
             "[Open the interactive viewer](../../assets/flows/index.html) to search all flows, click steps for their code and walk through them.", "",
             "| Flow | Module | Trigger | Outcome | Steps |", "| --- | --- | --- | --- | ---: |"]
    for fl in sorted(flows, key=lambda x: (x["module"], x["title"])):
        f = fl["_spec"]
        lines.append(f"| [{fl['title']}]({fl['id']}.md) | {f.get('module', '') or '—'} | {f.get('trigger', '') or '—'} | "
                     f"{f.get('outcome', '') or '—'} | {len(fl['steps'])} |")
    open(os.path.join(FLOWS, "index.md"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
